### ISSUE TITLE
(Enhancement) Acronyms with multiple definitions are confusing

### ISSUE THREAD

**Issue by michael-barlow3** [department-of-veterans-affairs/wtf-bot#11]
When entering "aaa" (which has multiple definitions), this is displayed:
![Current](https://user-images.githubusercontent.com/62751116/118292505-b2aa2d00-b4a6-11eb-833f-8a88110860b1.png)

It would be nice if the definitions could be displayed on multiple lines along with the acronym like:
![Updated](https://user-images.githubusercontent.com/62751116/118292582-c8b7ed80-b4a6-11eb-9948-7703c3090f0b.png)

**Comment by karlbrown-va** [comment]
Closed by #13
