### ISSUE TITLE
New bot photo

### ISSUE THREAD

**Issue by Moofasax** [department-of-veterans-affairs/wtf-bot#23]
To rien in the wtf-bots new home and overlord, i am requesting we honor him by changing the bots photo on slack

From:
![image](https://user-images.githubusercontent.com/25934977/166498970-19171c0e-a997-4b9e-8775-722773028e75.png)

To:
![image](https://user-images.githubusercontent.com/25934977/166498854-d41b5604-debe-42b0-9a0a-43c0ac4e5582.png)

It only seems right

**Comment by karlbrown-va** [comment]
This would be decided on a per-slack basis, so closing as not relevant to this repo...
