### ISSUE TITLE
Error message in wtf-bot

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/wtf-bot#32]
When I input an acronym using the wtf-bot that is an acronym that I know exists within the list, I get an error message saying acronym not found. See image below:

<img width="377" alt="image" src="https://github.com/department-of-veterans-affairs/wtf-bot/assets/71330581/774b7ad2-7444-4e1b-90cc-300b45f8afd9">

**Comment by karlbrown-va** [comment]
My best suggestion is to submit a ticket to DOTS which manages the bot. You can submit a ticket here:
https://jira.devops.va.gov/servicedesk/customer/portal/1

alternately you can ask for help on the [#dots-dsva](https://dsva.slack.com/archives/C01U8EYHSEM) channel in slack.

FWIW I did look into this briefly and corrected some formatting issues with the acronyms file but that doesn't seem to have fixed the issue.
