### ISSUE TITLE
Include "Context" and "Notes" in Slack message

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/wtf-bot#7]
There is useful info in the `Context` and `Notes` columns of https://github.com/department-of-veterans-affairs/acronyms/blob/master/acronyms.csv

This info should be included in the Slack response

Test cases:
`/wtf 3PAO` - should return context from https://github.com/department-of-veterans-affairs/acronyms/blob/master/acronyms.csv#L9
`/wtf ACAS` - should return notes from https://github.com/department-of-veterans-affairs/acronyms/blob/master/acronyms.csv#L60

**Comment by michael-barlow3** [comment]
The bot should also display the info from the `Context` and `Notes` columns in addition to any multiple definitions for a given acronym for example:
![context_notes](https://user-images.githubusercontent.com/62751116/118344625-1fe8ad00-b4fd-11eb-89fc-5272f3b15b29.png)
